package com.ewitulsk.villagersimulator.harness;

import com.ewitulsk.villagersimulator.api.sim.expr.ExpressionFunction;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/**
 * Generates {@code docs/EXPRESSIONS.md}, the expression-function reference, from the functions the base game
 * registers (docs/ROADMAP.md Phase 7). {@code ./gradlew :sim-harness:expressionReference} rewrites it; a test fails
 * when it's out of date.
 */
public final class ExpressionReference {
    private ExpressionReference() {}

    public static String markdown() {
        List<ExpressionFunction> fns = new ArrayList<>(Scenario.start().world().logic().functions());
        fns.sort(Comparator.comparing(ExpressionFunction::name));
        StringBuilder b = new StringBuilder();
        b.append("# Expression Function Reference\n\n");
        b.append("<!-- Generated by ExpressionReference (./gradlew :sim-harness:expressionReference). Do not edit. -->\n\n");
        b.append("Functions available in VS expressions: advertisement `score` and `condition` fields, effects and ");
        b.append("`/vs expr eval`. The syntax is described in [ARCHITECTURE.md §9](ARCHITECTURE.md#9-vs-expression-language). ");
        b.append("Addons add their own functions with `SimRegistrar.function`.\n\n");
        b.append("| Function | Description |\n|---|---|\n");
        for (ExpressionFunction f : fns) {
            String description = f.description().replace("|", "\\|");
            b.append("| `").append(f.signature()).append("` | ").append(description).append(" |\n");
        }
        return b.toString();
    }

    public static void main(String[] args) throws IOException {
        Path out = Path.of(args.length > 0 ? args[0] : "docs/EXPRESSIONS.md");
        Files.writeString(out, markdown());
        System.out.println("Wrote " + out.toAbsolutePath());
    }
}
